cargo-features = ["edition2024"]

[package]
name = "lautr"
version = "0.1.0"
edition = "2024"


[dependencies.datafrog]
version = "2.0.1"

[dependencies.pyo3]
version = "0.24.1"
features = ["extension-module"]

[dependencies]
nix-compat = { git = "https://github.com/mschwaig/snix", branch = "fanfic", package = "nix-compat" }

[lib]
name = "lautr"
crate-type = ["cdylib"]
