name: update-flake-lock
on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 15 * 1' # runs weekly on Mondays at 08:15

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "[bot] update flake.lock"
          token: ${{ secrets.GH_ACTION_LAUT_FLAKE_UPDATE_TOKEN }}
